#!/usr/bin/env python3
"""Create the 3 Cloud Environments via Anthropic's Beta Environments API.

Reads ANTHROPIC_API_KEY from env. Creates `general`, `day-trader-kraken`,
and `news-based` environment shells with unrestricted network and no
extra packages (our scripts use only Python stdlib).

⚠️  Limitation of the Beta API (as of 2026-04):
    The create endpoint does NOT accept environment variables, secrets,
    or setup scripts in the request body. After this script runs you
    still need to open each environment in claude.ai/code and:

      1. Paste the `.env` block from docs/SETUP.md → Part 1.
      2. Paste the setup script from docs/SETUP.md → Part 1.

    The script saves you the naming + network-policy + description
    typing — about 30% of the manual work per env.

Usage:
    export ANTHROPIC_API_KEY=sk-ant-...
    python scripts/create_environments.py

After it succeeds it prints the env IDs and the exact follow-up steps.
The IDs are also written to docs/.env-ids.txt so you can re-run safely
(the script skips envs whose name already exists in your account).
"""
from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request

API_BASE = "https://api.anthropic.com/v1"
BETA_HEADER = "managed-agents-2026-04-01"
ANTHROPIC_VERSION = "2023-06-01"

ENVS = [
    {
        "name": "general",
        "description": "Trading bot — general/swing strategy, beat-SPY",
    },
    {
        "name": "day-trader-kraken",
        "description": "Trading bot — day trader, single-name (KRKNF)",
    },
    {
        "name": "news-based",
        "description": "Trading bot — micro + macro news driven",
    },
]


def _key() -> str:
    k = os.environ.get("ANTHROPIC_API_KEY", "")
    if not k:
        sys.exit(
            "missing env var: ANTHROPIC_API_KEY\n"
            "Get one at https://console.anthropic.com/settings/keys\n"
            "Set it locally:  export ANTHROPIC_API_KEY=sk-ant-...\n"
            "Then re-run this script. Rotate the key after you're done."
        )
    return k


def _headers() -> dict[str, str]:
    return {
        "Content-Type": "application/json",
        "anthropic-version": ANTHROPIC_VERSION,
        "anthropic-beta": BETA_HEADER,
        "X-Api-Key": _key(),
    }


def _request(method: str, path: str, body: dict | None = None) -> dict:
    url = f"{API_BASE}{path}"
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method, headers=_headers())
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        sys.exit(f"{method} {url} -> {e.code}\n{e.read().decode()}")


def list_envs() -> list[dict]:
    out: list[dict] = []
    page = None
    while True:
        suffix = f"?page={page}" if page else ""
        resp = _request("GET", f"/environments{suffix}")
        out.extend(resp.get("data", []))
        page = resp.get("next_page")
        if not page:
            return out


def create_env(name: str, description: str) -> dict:
    body = {
        "name": name,
        "description": description,
        "config": {
            "type": "cloud",
            "networking": {"type": "unrestricted"},
            "packages": {},
        },
    }
    return _request("POST", "/environments", body)


def main() -> int:
    print("=" * 60)
    print("Creating 3 Cloud Environments via Beta API")
    print("=" * 60)
    _key()  # fail fast if missing

    print("\nListing existing environments to skip duplicates...")
    existing = {e["name"]: e["id"] for e in list_envs()}
    print(f"  found {len(existing)} existing")

    results: list[tuple[str, str, str]] = []  # (name, id, status)
    for env in ENVS:
        if env["name"] in existing:
            results.append((env["name"], existing[env["name"]], "EXISTS"))
            print(f"  - {env['name']:20s}  {existing[env['name']]:30s}  EXISTS — skipped")
            continue
        created = create_env(env["name"], env["description"])
        env_id = created.get("id", "<no id>")
        results.append((env["name"], env_id, "CREATED"))
        print(f"  + {env['name']:20s}  {env_id:30s}  CREATED")

    # write the IDs file
    ids_path = os.path.join(os.path.dirname(__file__), "..", "docs", ".env-ids.txt")
    ids_path = os.path.normpath(ids_path)
    with open(ids_path, "w") as f:
        f.write("# Auto-generated by scripts/create_environments.py\n")
        f.write("# These are environment IDs, not secrets — safe to commit.\n\n")
        for name, env_id, _ in results:
            f.write(f"{name}={env_id}\n")
    print(f"\nWrote env IDs to {ids_path}")

    print()
    print("=" * 60)
    print("NEXT STEPS — these still require the web UI:")
    print("=" * 60)
    print("""
For each environment above, open it in https://claude.ai/code and:

  1. Set network access to 'Trusted' (default — should already be).
  2. Paste the .env block from docs/SETUP.md → Part 1 into
     'Environment variables'. Replace the <placeholders> with your
     real keys. The Alpaca keys differ per environment — match the
     environment name to the right Alpaca paper account.
  3. Paste the setup script from docs/SETUP.md → Part 1.
  4. Save.

Then proceed to docs/SETUP.md → Part 2 to create the 16 routines.

⚠️  Rotate your ANTHROPIC_API_KEY after this script run, since you
    pasted it locally. (Console > Settings > API Keys > Regenerate.)
""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
